name: http_api_example
description: A example of flutter http_api package.
publish_to: none

version: 1.0.0

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  provider: ^6.0.4
  json_annotation: ^4.7.0
  http_api:
    path: ../
  flutter:
    sdk: flutter

dev_dependencies:
  build_runner: ^2.3.2
  json_serializable: ^6.5.4
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
