name: http_api_example
description: A example of flutter http_api package.

version: 1.0.0

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  provider: 4.0.5
  json_annotation: 3.0.1
  http_api:
    path: ../
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

dev_dependencies:
  build_runner: 1.7.3
  json_serializable: 3.2.5
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
