name: http_api_example
description: A example of flutter http_api package.
publish_to: none

version: 1.0.0

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  provider: ^5.0.0
  json_annotation: ^4.0.1
  http_api:
    path: ../
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

dev_dependencies:
  build_runner: ^2.0.4
  json_serializable: ^4.1.3
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
