name: http_api
description: A simple yet powerful wrapper around http package with interceptors/middleware support, along with response caching.
version: 0.9.0
repository: https://github.com/gonuit/flutter_http_api
homepage: https://github.com/gonuit/flutter_http_api
issue_tracker: https://github.com/gonuit/flutter_http_api/issues

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  http: ^0.13.3
  meta: ^1.1.1
  objectid: ^2.0.0
  http_parser: ^4.0.0

dev_dependencies:
  effective_dart: ^1.2.0
  mockito: ^5.0.10
  test:
