name: http_api
description: A simple yet powerful wrapper around http package with middleware support.
version: 0.1.0
author:
homepage:

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  http: ^0.12.0+4
  meta: ^1.1.8
  http_parser: ^3.1.4
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

