name: http_api
description: A simple yet powerful wrapper around http package with interceptors/middleware support, along with response caching.
version: 0.7.3
repository: https://github.com/gonuit/flutter_http_api
homepage: https://github.com/gonuit/flutter_http_api
issue_tracker: https://github.com/gonuit/flutter_http_api/issues

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  http: ^0.12.1
  meta: ^1.1.8
  objectid: ^1.1.1
  http_parser: ^3.1.4

dev_dependencies:
  effective_dart: ^1.2.0
  mockito: ^4.1.1
  test:
